### ISSUE TITLE
Full IPv6 support

### ISSUE THREAD

**Issue by statianzo** [statianzo/Fleck#120]
PR #119 brought support for listening on IPv6 when listening on `0.0.0.0` or `[::]`. Fleck should also support explicit IPv6 addresses as well.

**Comment by parnham** [comment]
The latest nuget release (0.12) which includes the IPv6 support mentioned in the pull request actually causes exceptions to be thrown when run under mono (testing on linux). At the line https://github.com/statianzo/Fleck/blob/master/src/Fleck/WebSocketServer.cs#L28 mono does not actually contain a definition for ```SocketOptionName.IPv6Only```.

Another [project](https://github.com/TehGimp/KerbalMultiPlayer/blob/master/KMPServer/Server.cs#L667) tries to handle this situation as follows:

```csharp
try
{
    //Windows defaults to v6 only, but this option does not exist in mono so it has to be in a try/catch block along with the casted int.
    tcpListener.Server.SetSocketOption(SocketOptionLevel.IPv6, (SocketOptionName)27, 0);
}
catch
{
    Log.Debug("Failed to unset IPv6Only. Linux and Mac have this option off by default.");
}
```

Alternatively it would have to use two separate sockets and therefore avoid the need to set this option.

**Comment by statianzo** [comment]
My bad for not catching it. The Mono CI server I was piggybacking on is gone. Travis CI might be an alright choice for filling that gap.

**Comment by statianzo** [comment]
@parnham Test out Nuget release Fleck 0.12.0.37. It includes the changes from #121

**Comment by parnham** [comment]
I'm afraid that had no effect, running 0.12.0.37 we still get the exception:

```
System.Net.Sockets.SocketOptionName 0x1b is not supported at IPv6 level

Unhandled Exception:
System.Net.Sockets.SocketException: Protocol option not supported
  at System.Net.Sockets.Socket.SetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName, Boolean optionValue) [0x00000] in <filename unknown>:0
```

**Comment by statianzo** [comment]
Ahh. It's because the nuget is compiled with a .NET compiler. Building using Mono would pay attention to the compiler conditionals. For the Nuget to work, the lack of IPv6 needs to be detected at runtime.

**Comment by rickparrish** [comment]
http://www.mono-project.com/docs/gui/winforms/porting-winforms-applications/ has this snippet for runtime detection of mono:

  public static bool IsRunningOnMono ()
  {
    return Type.GetType ("Mono.Runtime") != null;
  }

**Comment by rlweb** [comment]
https://github.com/statianzo/Fleck/pull/124
I've left the Mono compiler flag in so I am able to compile the project for my solution.

**Comment by parnham** [comment]
Just updated our project with the latest nuget and that appears to have done the trick. Thank you!

**Comment by statianzo** [comment]
Great work, @rlweb!
