### ISSUE TITLE
Questions related to selection of websocket library

### ISSUE THREAD

**Issue by jakubbukaj** [statianzo/Fleck#122]
Hello,
Thank you for great work. Currently I am looking for suitable component for handling WebSockets in my application. I would like to ask you some questions.

1) Is it possible to easily broadcast some message to all connected clients?
2) Do you plan to add some HTTP Authentications? Basic, Digest
3) Do you plan to write web socket client as part of this great library?
4) I see this project is actively developed mainly by Statianozo. Can you please let me know how serious is this project for you and whether there is a chance this project will not be abandoned in year or two?
5) Could you find relevant reasons why to choose Fleck instead of websocket-sharp?

Thank you very much

**Comment by statianzo** [comment]
1. Sure. If you keep a list structure of all sockets you can invoke Send() on them at any time.
2. I don't have plans for adding HTTP Auth right now. I'd gladly accept a pull request. If you were insistent on using Fleck with Auth, I'd put a reverse proxy like nginx in front of it.
3. No intentions of creating a client.
4. I'd consider the project passively maintained by me. I respond to issues and pull requests, but am not actively coding.
5. That's a decision you'll have to make by evaluating both.

**Comment by rickparrish** [comment]
I could be wrong, but IIRC websocket-sharp doesn't support pre-RFC versions of WebSocket.  They have older branches that support them, but that doesn't do you any good if you want to support all versions from a single library.

May not be a big deal to some people, but some older mobile devices don't (and won't ever) support the RFC, so it's definitely something to keep in mind.

**Comment by jakubbukaj** [comment]
Thank you very much for answers.
