### ISSUE TITLE
Specifying byte array offset and size when calling Send

### ISSUE THREAD

**Issue by galbarm** [statianzo/Fleck#123]
Hello,
The signature of IWebSocketConnection.Send accepts a byte[] as a parameter.
However, there is no way to specify the offset/size to actually send from the byte array.

In my use case, it forces an extra redundant copy from the original byte array, to another byte array that fits in the exact size that I actually need to send.

**Comment by CorneliuCincea** [comment]
Hello guys,
I would like to implement this feature, but I need help on how I will implement these methods. Should I modify the signature from the existing interface ? Or create a new interface with the methods which has in signature the offset and size ?

**Comment by galbarm** [comment]
I would suggest leaving the signature of send intact and go for creating an overload of Send.
The existing Send will call the new overload with the params: (buffer, 0, buffer.Length)

**Comment by Narmdo** [comment]
Any news on whether this feature is coming?

**Comment by statianzo** [comment]
@Narmdo It's not actively being worked on. I'll accept a PR if you're interested in taking it on.
