### ISSUE TITLE
Cannot connect from WP81 MessageWebSocket client to Fleck server

### ISSUE THREAD

**Issue by JRGit4UE** [statianzo/Fleck#129]
Hi, I try to connect from 
WP81 C# app using Microsofts *MessageWebSocket* to Fleck C# server on Win81. 
Fleck Version is 12.0.37.
WLAN is working, firewall is off, I can ping the phone, but there is no connection between WP client and Fleck server established. 
Using a Microsoft *WebSocketClient* as server on Win 8.1 works with WP81 *MessageWebSocket* client app. 
Using a *WebSocket4Net* client on Win 8.1 works with Win8.1 Fleck *IWebSocketConnection* server as well...
I'm sort of desparate now...
Wireshark protocol shows retransmission tries:
1	0.000	192.168.0.103	192.168.0.1	TCP	66	49708→9000 [SYN] Seq=0 Win=65535 Len=0 MSS=1460 WS=256 SACK_PERM=1
2	0.884	192.168.0.103	192.168.0.1	TCP	66	[TCP Retransmission] 49708→9000 [SYN] Seq=0 Win=65535 Len=0 MSS=1460 WS=256 SACK_PERM=1 

Can anybody give me an idea whats going wrong?

**Comment by statianzo** [comment]
Can you set `FleckLog.Level = LogLevel.Debug` and share the output?

**Comment by JRGit4UE** [comment]
Forgot this to mention, with LogLevel.Debug there is *no output*...

**Comment by JRGit4UE** [comment]
Here is the WP81 C# code
                    Uri server = new Uri("ws://192.168.0.1:9000/Operator1TouchSensor/");
                    w = new MessageWebSocket();
                    w.Control.MessageType = SocketMessageType.Utf8;
                    w.MessageReceived += MessageReceived;
                    w.Closed += ConnectionClosed;

                    await ShowStatusMessageAsync("Connecting to " + cfg.ServerIPAddress);
                    await w.ConnectAsync(server);
                    messageWriter = new DataWriter(w.OutputStream);

**Comment by statianzo** [comment]
If the Log set to Debug shows nothing, then the server isn't getting reached by the phone at all. Fleck will log a "Client Connected" message upon any connection.

In your other tests, like the WebSocket4Net client, were you testing from a remote client or on the same machine as the server?

**Comment by JRGit4UE** [comment]
Unfortunately, there is no WP81 implementation of *WebSocket4Net* version 0.11 (only for WP80, which is incompatible), so I have tested it from the same machine as the Fleck server.

**Comment by statianzo** [comment]
Try testing from a remote computer with one of the working websocket clients you've used and see if you're getting the same result as on the phone.

**Comment by JRGit4UE** [comment]
"*If the Log set to Debug shows nothing, then the server isn't getting reached by the phone at all.*"
Hi, thanks for your suggestions, as you have pointed out, I removed all network-  and firewall related settings, reactivated the network and now all troubles are gone...
Thank you!

**Comment by statianzo** [comment]
Glad to hear it, good luck on your project!
