### ISSUE TITLE
Is Deflate per Message or per Frame supported?

### ISSUE THREAD

**Issue by jogibear9988** [statianzo/Fleck#136]

**Comment by statianzo** [comment]
Deflate is not supported by Fleck. If anyone's up for the task, I'd accept a pull request.

**Comment by BrandonLWhite** [comment]
I would love this.  I came across Fleck because I am trying to implement WebSockets with SignalR from an OWIN self-hosted service/daemon app in Linux using Mono.  And my whole point in using WebSockets is so I can do permessage compression.
