### ISSUE TITLE
About the use

### ISSUE THREAD

**Issue by pexison** [statianzo/Fleck#139]
Please it is possible to have a short information about how to install it? (The actual version gives me "rake aborted!") see this: https://github.com/Albacore/albacore/issues/136

**Comment by statianzo** [comment]
You need to be using a 1.0 version of albacore for the rake task to work.

The typical way of using would be through Nuget.  http://www.nuget.org/packages/Fleck/
You can also download artifacts from the latest CI build. http://build.fubu-project.org/viewType.html?buildTypeId=bt21

You can also build it yourself by just opening the src/Fleck.sln with visual studio and building it.
