### ISSUE TITLE
Empty HTTP header in handshake

### ISSUE THREAD

**Issue by jahto** [statianzo/Fleck#140]
I'm not sure whether the actual bug is in Fleck or Intel XDK. Depends on what's the right interpretation of http://tools.ietf.org/html/rfc2616, point 4.2. I think that it says that a header not having a value can end with :\r\n not having a space between them. Interpreting standards correctly is sometimes a bit hard.

Now, the problem is that opening a websocket when in emulator mode in Intel XDK, it sends one empty header (User-Agent:\r\n) without any space and the regular expression in Fleck.RequestParser assumes there must be one. So I propose a change to line 9 in that file.

```
 --- @"((?<field_name>[^:\r\n]+):\s(?<field_value>[^\r\n]*)\r\n)+" + //headers
 +++ @"((?<field_name>[^:\r\n]+):\s*(?<field_value>[^\r\n]*)\r\n)+" + //headers
```

I'm not forking the project and making a pull request later because this seems to be really a minor issue, and the actual bug might be in Intel XDK, if the right interpretation actually is that even an empty header must have linear white space after :.

But, at least, making that small change to my local clone cured my problem.

Thanks and my best wishes for anyone working on this project. I might even contribute some small things to it later, because I'm going to use it myself and if I find something other, or just good ideas.

**Comment by weikaolun** [comment]
I've confirmed this fix for the Electron/NW.js WebSocket implementations, which also omit whitespace in the empty User-Agent header.
