### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by Chaz27** [statianzo/Fleck#141]
I have a web socket running using secure connections.  A scan reveals that the protocol is TLS 1.0.  Is there any way to enable TLS 1.2?

**Comment by artfulhacker** [comment]
How did you do this scan? might be registry setting on the windows machine, I can scan mine and tell you if it is.

**Comment by Chaz27** [comment]
Hi, I have it running on a Windows 2012 server on amazon.  Scan is done by this site: https://www.ssllabs.com/ssltest/

Cheers!

**Comment by artfulhacker** [comment]
Seeing the same thing on our windows machine as well :-/

**Comment by statianzo** [comment]
The problem is `SslProtocols.Tls` here:
https://github.com/statianzo/Fleck/blob/master/src/Fleck/SocketWrapper.cs#L53

The code was written against .NET 4.0, which doesn't support the Tls11 and Tls12 options.
https://msdn.microsoft.com/en-us/library/system.security.authentication.sslprotocols(v=vs.110).aspx

Detecting the latest version at runtime with TryParse could do the trick.

**Comment by artfulhacker** [comment]
maybe it can be exposed as a pubic member so we can do this:

var server = new WebSocketServer("wss://0.0.0.0:8431");
server.Certificate = new X509Certificate2("MyCert.pfx");
server.enabledSslProtocols = SslProtocols.Tls12;
server.Start(socket =>
{
  //...use as normal
});

if you like it I can make the pull request

**Comment by statianzo** [comment]
I dig that idea. Will let users of Fleck pick what they want. Send a PR.

**Comment by artfulhacker** [comment]
If the parent project is >.NET 4.0 then they should be able to specify the Tls11 or Tls12, I added a test to check for the default initialization so we could always fallback to Tls and added a debug entry in case this comes up again it will be a little more obvious what the default behavior is.

**Comment by e4ky** [comment]
非常棒，解决的我的问题。

**Comment by vinibeloni** [comment]
`this.server.EnabledSslProtocols = (SslProtocols)3072;`

works for me (I know that possibly have an problem with windows xp)
