### ISSUE TITLE
Memory leak for every Connected/Disconnected client

### ISSUE THREAD

**Issue by sanychsamara** [statianzo/Fleck#145]
It appears that Fleck server leaks a little memory for every new client. The memory is not getting released after client is disconnected. 

I put together a small test app, which is just a 

```
var server = new WebSocketServer("ws://127.0.0.1:3842/channel");
server.Start(socket =>
{
    socket.OnMessage = message => socket.Send(message);
});
```
Here is zip of the solution + test client. 
http://temp.sanych.org.s3.amazonaws.com/FleckTests.zip

Steps to reproduce 
- Start server
- Start runme.bat from the client folder
- Write down memory usage
- Let it run for 5 min, notice that memory increased
- Notice that memory increases every min forever
- It will eventually use all available PC memory (though it may take couple days of running)

It is also clearly visible with Visual Studio 2015 "memory snapshot" functionality. Here is a screenshot showing difference between 2 memory snapshots only few seconds apart

![memory-leak-screenshot](https://cloud.githubusercontent.com/assets/2152643/9072133/46255466-3aae-11e5-83b4-d9a262249b9f.png)

**Comment by statianzo** [comment]
If you remove the `socket.OnMessage = message => socket.Send(message)` line, does it still leak?

If it no longer leaks, try an `OnMessage` callback without the `socket.Send` to see if that causes it.

**Comment by sanychsamara** [comment]
It leaks the same even without "socket.OnMessage" line. Screenshot of a 1 min diff attached. Notice that profiler detected a reference "cycle" in Fleck.WebSocketConnection
![memory-leak-screenshot2](https://cloud.githubusercontent.com/assets/2152643/9090584/f0fcec04-3b4f-11e5-934c-22fdc44528f5.png)

**Comment by statianzo** [comment]
I see there's a List<IWebSocketConnection>, I'm curious where that's coming from.

**Comment by darkl** [comment]
@sanychsamara, I can say I ran not long ago load tests involving a Fleck server and found no memory leaks (for ~16K connections that come and ago).
What I can suggest you is to send pings to your clients to detect if they're still alive, since I suspect your WebSocketServer doesn't detect some client disconnections which results in memory leaks of these connections.

**Comment by sanychsamara** [comment]
I put back console logging on "OnOpen" and "OnClose" and you can see that OnClose is getting called. I updated zip with test solution: http://temp.sanych.org.s3.amazonaws.com/FleckTests.zip

Here are 2 screenshots of memory usage about 1 min apart (~30 clients connected/disconnected in that time). To reproduce all you need to do is ti run apps from the test solution (see zip above) 

![memory-leak-screenshot2](https://cloud.githubusercontent.com/assets/2152643/9096857/bdc3179e-3b74-11e5-88c1-e863f1b976a3.png)

![memory-leak-screenshot3](https://cloud.githubusercontent.com/assets/2152643/9096860/c40b50f8-3b74-11e5-96d5-673cfdacea79.png)

**Comment by darkl** [comment]
I prefer you to post these as gists in github gists than downloading a zip and running a bat.
Anyways, my test server calls Console.Readline(); GC.Collect(); in a while true loop in the end of the main. After disconnecting all clients I press enter a couple of times and the memory gets stable. (Even after connecting and disconnecting lots of clients (~16K) it converges to a stable value)

**Comment by sanychsamara** [comment]
I am sorry, but after

- I showed a 5-line long snipped (which is a copy-paste from the Fleck docs) of the server code
- I gave you the full kit of the server and client 
- I gave you screenshots of both Windows OS and Visual Studio 2015 showing growing memory

answering that "it used to work on my desk" is not very helpful. 

If you have a client/server testing kit that handles 16K clients and never grows beyond 100M - please post it here.

**Comment by darkl** [comment]
Ok, I asked for your client code so I won't have to rewrite this all thing myself, but I managed to write it anyways.

[Client](https://gist.github.com/darkl/7436f490dd7efd705ceb)
[Server](https://gist.github.com/darkl/64bb30a5db0f876bdb00)

The client requires WebSocket4Net.

Instructions:
* Run a server
* Run a client
* press enter on the client - this will open 4000 connections to server (wait till number gets to 4000 or stabilizes at some close value)
* Run another client (don't close the previous one)
* press enter on the other client - this will open another 4000 connections. (wait till number gets to 4000 or stabilizes at some close value)
* Open task manager, look at server memory (Should be > 200MB)
* Close clients (via CTRL+C)
* Wait one minute
* Go to server and hit enter. Hit it a few times. Memory usage of server should decrease. It it doesn't, wait a few longer and hit enter a few more times.
* Task manager server's memory should be 7-10MB.

**Comment by sanychsamara** [comment]
Thank you for the test project. I have been running tests last night and here are my findings so far

1. For non-SSL connections GC.Collect() seems to do the job. Though it is mandatory to call it periodically. It doesn't matter for how long server is running or how idle it is. It will never report memory back to OS unless you call GC.Collect(). So I think the note about mandatory GC.Collect() should go to the docs.

2. The test results were inconclusive about SSL connections. I have not seen memory size completely settling, though with GC.Collect() every 1000 connections it grows at much slower rate. 

Since on production we already terminate SSL on Nginx and run Fleck-based server in non-SSL mode - GC.Collect() is good enough for us. Sandbox gets restarted often enough that even if there is a small leak in SSL mode - we do not care for now.

Thank you for your help!

**Comment by darkl** [comment]
@sanychsamara, you welcome.

I'm ain't no NET memory expert, but I consider calling GC.Collect yourself explicitly a bad practice.
You should least be aware about how the GC works (one recommends CLR via C# chapters about GC), and read stackoverflow questions about when to call GC.Collect, and why doesn't the GC free memory automatically in this case (See these questions [#1](http://stackoverflow.com/questions/10016541/garbage-collection-not-happening-even-when-needed?lq=1) [#2](http://stackoverflow.com/questions/478167/when-is-it-acceptable-to-call-gc-collect) [#3](http://stackoverflow.com/questions/118633/whats-so-wrong-about-using-gc-collect) [#4](http://stackoverflow.com/questions/16142182/why-do-i-have-to-call-gc-collect-explicitly))

Not saying this is totally bad, but you should be aware about this.

**Comment by StevenBonePgh** [comment]
I second @darkl 's comments.  This is definitely a situation where GC knows far more than you do about when to relinquish memory.  By doing this, it is likely to create performance problems. The references he refers to here are excellent.

**Comment by lu4** [comment]
Any news on this one?

**Comment by artfulhacker** [comment]
@lu4 if you are worried about using this in production, I use fleck in production under a very heavy load  and do not have any issues with a memory leak. memory goes up and then back down with usage (respectively).
