### ISSUE TITLE
"An address incompatible with the requested protocol was used" on XP

### ISSUE THREAD

**Issue by Slayer91** [statianzo/Fleck#150]
Works well in all other OS above XP. The solution is in .net 4.0 vs10 .

When I come to creating the server using:
var server = new WebSocketServer("wss://127.0.0.1:8080"); 
I get Error   "An invalid argument was supplied."

or

var server = new WebSocketServer("wss://0.0.0.0:8080");

I get the Error:   "An address incompatible with the requested protocol was used"

any suggestions? 

Thanks

**Comment by statianzo** [comment]
Is the cert SHA-256? If so, XP doesn't support it.

**Comment by Slayer91** [comment]
Thats a good point and mine is SHA-256 so I shall have to change that thanks. However I don't issue the cert via 
server.Certificate = myCertificate;

untill after
  
var server = new WebSocketServer("wss://127.0.0.1:8080");

**Comment by statianzo** [comment]
Strange. Do you still get the message if you use `ws://127.0.0.1:8080` or only with `wss`?

**Comment by Slayer91** [comment]
Yes I still get that message. 

Also I apologise as I have presented an error wrong I also get a  "An invalid argument was supplied." when using "127.0.0.1" I will update the First post  to reflect it

**Comment by statianzo** [comment]
Ahh. It may be stemming from the IPv6 related code in
https://github.com/statianzo/Fleck/blob/master/src/Fleck/WebSocketServer.cs#L33

**Comment by Slayer91** [comment]
This was my suspicion. I have tried [::1] with no success though

**Comment by Slayer91** [comment]
Just installing ipv6 on the xp machine and trying it out.

**Comment by Slayer91** [comment]
After installing IPv6 i now get a different error "An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call"....

**Comment by recallfx** [comment]
I changed the line @statianzo mentioned to `socket.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.IPOptions, true);` and got it working on windows XP.

**Comment by radioman** [comment]
@recallfx i get crash on xp, did you changed anything else?
