### ISSUE TITLE
Could this be run under .NET 3.5 Compact?

### ISSUE THREAD

**Issue by rickard-505** [statianzo/Fleck#157]

**Comment by statianzo** [comment]
Fleck targets .NET 4.0.
There is a  [net35 branch](https://github.com/statianzo/Fleck/tree/net35) that has .NET 3.5 support, but I couldn't tell you if it would work on 3.5 Compact. Give it a try, and if anything, it could be a good starting point for you.

**Comment by rickard-505** [comment]
Seem Compact does not have needed
Error   2       The type or namespace name 'WebSocketServer' could not be 
found (are you missing a using directive or an assembly reference?) 
C:\Users\ricka_000\Documents\Visual Studio 
2008\Projects\DDETest\DDETest\Program.cs        22      30      DDETest
