### ISSUE TITLE
Handshake problem

### ISSUE THREAD

**Issue by kidol** [statianzo/Fleck#158]
The following doesn't work. In Firefox console it says resource couldn't be loaded. In Chrome it works most of the time, but not always. Apparently the handshake is not fully executed?

```c#
socket.OnOpen += delegate
{
	socket.Send("test").Wait();
	socket.Close();
};
```

It works as expected if I either add a sleep before `socket.Close()`:

```c#
Thread.Sleep(50);
```

Or if I remove `socket.Close()`.

Any idea? It seems like `Send()` does return before the handshake is complete, but at quick glance I couldn't spot mistake in code (I'm new to task pattern though).

**Comment by statianzo** [comment]
Instead of blocking the thread with `Wait()` try using
```csharp
socket.Send("test").continueWith(() => socket.Close());
```

**Comment by kidol** [comment]
Nope, doesn't work. I guess I have to dive in deeper and set breakpoints...
Just thought maybe that's a known issue or there is a known solution.
Well I will look into it tomorrow and post results.

I also tried other library (vtortola.WebSockets) and there is no such problem, it has other issues though (also task related it seems).

**Comment by kidol** [comment]
So what I did was adding a lock to `SocketWrapper.Send()`, it is released after `_stream.EndWrite(asyncResult)` is called: There does not seem to be an overlap in `Send()` calls. I also verified this by writing all bytes to a file - all packets were in correct order.
Also made sure the lock is not active when `SocketWrapper.Close()` calls `_stream.Close()` and `_socket.Close()`.

Tried setting `Socket.NoDelay` to `false`, `Socket.BufferSize` to `1`. Tried some other things...
Here screenshots of a successful and a failed request:

![success](https://cloud.githubusercontent.com/assets/440902/12846215/787ba37c-cc0b-11e5-9eb3-fde6bccb1d36.jpg)
![error](https://cloud.githubusercontent.com/assets/440902/12846220/7fc85a62-cc0b-11e5-9a42-0c095edfe72c.jpg)

I doubt it's a browser bug because like I said, happens on Chrome too once in a while. Also the other library works fine with Firefox on this use case.

Feel free to close if you have no more idea.

**Comment by statianzo** [comment]
Code 1006 [means Abnormal Closure](https://github.com/statianzo/Fleck/blob/master/src/Fleck/WebSocketStatusCodes.cs), meaning an exception was thrown inside Fleck. Set `FleckLog.LogLevel = LogLevel.Debug` and you'll see the exception that was thrown printed to the console.

**Comment by kidol** [comment]
Thanks that helps.

> 05.02.2016 17:57:31 [Debug] Client connected from ::ffff:127.0.0.1:9684
05.02.2016 17:57:31 [Debug] 510 bytes read
05.02.2016 17:57:31 [Debug] Building Hybi-14 Response
05.02.2016 17:57:31 [Debug] Sent 129 bytes
05.02.2016 17:57:31 [Debug] Sent 5 bytes
05.02.2016 17:57:31 [Debug] Sent 4 bytes
05.02.2016 17:57:31 [Debug] Swallowing ObjectDisposedException System.ObjectDisp
osedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.NetworkStream".
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,
 Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchro
nization)

Seems like Chrome stil processes the output of the first frames even if the connection is has a problem later on. Firefox just discards everything.

Do you know what to make of this exception?

**Comment by kidol** [comment]
I've now added try-catch around the EndRead.

Success:
![success](https://cloud.githubusercontent.com/assets/440902/12853725/fc3c27de-cc35-11e5-8821-d4c69b63dcd6.jpg)
Failure:
![error](https://cloud.githubusercontent.com/assets/440902/12853739/04cf9b1a-cc36-11e5-83d2-67a7b981b20e.jpg)

Could it be that Fleck needs to wait for the 8 byte response? Seems related to #130?

**Comment by statianzo** [comment]
The swallowed `ObjectDisposedException` comes from a read finishing after the socket has been closed. That's expected because we can't always cancel a read that's in flight. You can also add a listener to the `onError` handler inside the `start()` call and that will pass through any non-ObjectDisposed errors. Might give you more insight.

**Comment by kidol** [comment]
Closing this, it's duplicate of #130.
