### ISSUE TITLE
Disable Nagle / set TCP NoDelay

### ISSUE THREAD

**Issue by Vandroiy** [statianzo/Fleck#159]
After wasting days on inexplicable lag, I figured out that Fleck is using Nagle's algorithm to delay small messages. **This was adding over 200% to the latency to Windows 7 clients.** I "solved" the issue with a very questionable cast:

`(con :?> WebSocketConnection).Socket.NoDelay <- true`

where `con` is _supposed_ to be typed as an `IWebSocketConnection` and `:?>` is F# for "I know what this is, just downcast it". I am well aware that this abuses implementation details. But I don't know how else I am supposed to do this. I see that `NoDelay` is exposed on `ISocket`, but how do I get from `IWebSocketConnection` to `ISocket`?

It's probably a very bad idea to enable such an "optimization" by default. It should require an explicit parameter. The details of ack-delaying and subsequent lag depend on all kinds of circumstances, such as OS, browser, whether the client is local, funny registry settings, the size of server messages, the frequency of client messages, and probably more. Thus, the problem might not be noticed until production use and create mysteriously unreliable software.

I hope I made a good point that this should absolutely not be default behavior. Please either disable it in all cases or require an explicit parameter to enable it and document it with ample warnings. It is borderline untestable and should only ever be used where latency is not an issue.

**Comment by statianzo** [comment]
Does it work by setting NoDelay on `WebSocketServer.ListenerSocket`?

**Comment by Vandroiy** [comment]
Surprisingly, this does remove the problem. I don't know why though. The sockets are not equal from what I can tell; does the socket for an individual connection somehow inherit the listener socket's settings?

I think this would benefit from applying the principle of least astonishment. Is this the intended way to establish responsive connections?

**Comment by statianzo** [comment]
The listener socket provides a new instance on connection that apparently does carry over the settings.
This was the intended purpose of exposing NoDelay on ISocket. Someone created a PR with it. Glad to hear that it works for you. Perhaps a short piece of documentation would help future non-Nagle seekers. I'll take care of it.
