### ISSUE TITLE
HttpHandler

### ISSUE THREAD

**Issue by NVentimiglia** [statianzo/Fleck#160]
I would like to host Flex on an ASP MVC server. I understand I will need to include an http handler to support sharing of port 80. Is this an included feature, or is this something that I would need to write myself ?

I noticed this post from 2012
https://github.com/statianzo/Fleck/issues/48

Looks like someone already crossed that bridge and was hoping the bits were now included in the main library.

**Comment by statianzo** [comment]
It's something you'd need to take care of yourself. Likely what you'd want to do is to reverse proxy to the fleck service.

**Comment by NVentimiglia** [comment]
Ok, I will look into this. Any documentation on doing this (msdn, blogs, ect) would be helpful.

**Comment by statianzo** [comment]
I'm most familiar with nginx. 

https://www.nginx.com/resources/admin-guide/reverse-proxy/

**Comment by statianzo** [comment]
Looks like IIS can do reverse proxying as well. I haven't used it myself though: https://developers.coveo.com/display/public/SearchREST/Configuring+HTTPS+Reverse+Proxy+in+IIS;jsessionid=F44EDBB2099CE3A4CC86F70CF62321B7

**Comment by NVentimiglia** [comment]
I was able to connect on local host easy, so long as the port is open.
