### ISSUE TITLE
send binary file (images) to client

### ISSUE THREAD

**Issue by ellLazar** [statianzo/Fleck#161]
1.
how the  webSocket server send binary files like images ?
so javascript chrome will render the image in webpage ?
any syntax code example or link about,on javaScript side also, will help.

2. 
streamer
can the Fleck web server send with streamer object ?

3.
can webSocket server handle  from javascript .src request ?
in javascript : image.src="//hostname:8181/images/myImage.gif" 
and the websocket serving the request, as standard IIS ?

**Comment by statianzo** [comment]
1. Use the overload of `Send()` that accepts a `byte[]`. On the javascript side your onmessage callback's data will be a blob or arraybuffer.

2. Fleck doesn't support sending streams directly.

3. No, you can't use the websocket server to serve gifs. Use a normal http server.

**Comment by ellLazar** [comment]
<<Use a normal http server.>>
is it possible to combine the websocket and http server on same port ?
so to serve the websocket it will be ws:... 
and http request standard web server or my Http litener will server.
mostly only one port (80 , 443) are opened.

**Comment by statianzo** [comment]
You'd need to set up a reverse proxy to do that. A service that sat in front of both your services on port 80, and forwards to the correct upstream based on the scheme used (ws or http).

Take a look at this for an example of using IIS to reverse proxy
https://developers.coveo.com/display/public/SearchREST/Configuring+HTTPS+Reverse+Proxy+in+IIS;jsessionid=F44EDBB2099CE3A4CC86F70CF62321B7
