### ISSUE TITLE
how to get querystring name=value from message ?

### ISSUE THREAD

**Issue by ellLazar** [statianzo/Fleck#162]
is there methods to from message the query string all (name,value) ?
something like:
valName = message.QueryString["name"];
valAdrs  = message.QueryString["adrs"];

**Comment by statianzo** [comment]
I'm not sure what you mean. Can you elaborate?

**Comment by ellLazar** [comment]
querySTring is a part of url after '?' means:
//localhost/index.htm?name=name1&adrs=adrs1
querySTring={name=name1&adrs=adrs1}
queryString["name"]=name1
...
I need it juest for info

**Comment by statianzo** [comment]
I know what a query string is. I just don't understand which query string you want to read off.

The query string when making the websocket connection?
```js
new WebSocket('ws://example.com/endpoint?name=foo&age=25')
```

Or of the page your browser is on?

**Comment by ellLazar** [comment]
yes to the :
<<The query string when making the websocket connection?>>
the second:
<<Or of the page your browser is on?>>
I never used, and I don't know how to handle it.

**Comment by statianzo** [comment]
Look at `socket.ConnectionInfo.Path`. You'll have to parse out the parameters on your own.
