### ISSUE TITLE
Failed to parse the IP address part of the location (Whit "localhost")

### ISSUE THREAD

**Issue by Jshigueras** [statianzo/Fleck#164]
Hello!
Im trying to make it works in a "console Application project" with the url wss://localhost:10112 and i have this Error

"Additional information: Failed to parse the IP address part of the location. Please make sure you specify a valid IP address. Use 0.0.0.0 or [::] to listen on all interfaces."

I would like to know too if its possible to run a console application server in IIS.
It is posible to run Fleck in a Web Project? i've tried to do it but i have many problems. What would be the best choice?

Thanks

**Comment by AdrianBathurst** [comment]
If you need to run an app you could run a console app on the server (standalone, not in IIS), but you'd probably be better off running it as a service if the server is not always logged in.

For your server location, use `wss://0.0.0.0:10112`
Browser location use `wss://localhost:10112`

You will need to load a matching ssl certificate on socket server launch. Maybe get it all running without ssl to start with (`ws://`), then when it's all working, try convert it to use ssl (`wss://`)

You can run Fleck in a "Web Application" which is my preferred method, just put your code into the `Application_Start` method of global.asax.cs

**Comment by Jshigueras** [comment]
Alright.. I have compile and publish a web application with the server code. I can comunicate sucessfuly with the client in ws, but not in wss
I see 2 problems:

When i compiled, the project properties set the url to http:localhost:58902... but when i initialize the Websocket i set the 10112.. if try to change this second port to 58902, i have a 'System.Net.Sockets.SocketException'. If the port is different i can initialize succesfully. I have the same issue with IIS  with 443.

I've tried with a selfsigned certificate create by IIS, but the client cant connect with the Server. I've tried setting difrerents URL's in the client.. https://localhost:58902, https://192.168.1.27:58902...wss://localhost:58902... etc

I need some help
Thank you

**Comment by AdrianBathurst** [comment]
ok, it took me quite a bit of experimenting to get it working for me a while back. Here is a log of the process I followed, hopefully accurate as I was trying various ways...

**To get wss sockets & ssl working with iis express**

- run your site in visual studio under ssl using internet explorer (project properties > SSL enabled: true)

- in internet explorer, click the ssl padlock in the address bar & view the certificate properties.

- click the button "install certificate", installing the certificate in the location "Trusted Root Certification Authorities" of "Local Machine/Computer"

- run mmc.exe in cmd, select File > add/remove snap-in, select certificates. (for "manage certificates for", select "my user account")

- in certificate manager, browse to Personal > Certificates

- find & select the localhost certificate & right click it, select all tasks > export

- "yes" to export private key

- Export format: "Personal Information Exchange" & select "Include all certificates in the certification path"

- save the certificate to a location of your choice

- if you add a password to the exported file, you'll need it below

- load certificate with socket server:
```
var server = new WebSocketServer("wss://0.0.0.0:10112");
server.Certificate = new X509Certificate2("C:\path-to-certificate\certificate.pfx", "certificate-password");
```

GIVE THIS FOLDER FULL PERMISSIONS TO "EVERYONE":

C:\Documents and Settings\All Users\Application Data\Microsoft\Crypto\RSA\MachineKeys
*or it may be this path...*
C:\Documents and Settings\All Users\Microsoft\Crypto\RSA\MachineKeys

Folder above I'm guessing is where temporary instances of certificates are generated. This was definitely required on the server, maybe as a result of us locking down the server quite severely!

- run & test your site

> notes

> browser address bar must be https://localhost:1234 *(any port number, this is assigned by visual studio, this port is not used by sockets at all)*

> browser socket connection must be wss://localhost:10112 *(same port number as assigned to websocket server)*

> on a production server, to get a copy of the certificate, don't get it via the method above, you export it from IIS instead.

> browser socket connection domain name must match the domain name used in the browser address bar, **don't use an ip address**. secure sockets uses domain names, not ips to create a valid secure connection.
