### ISSUE TITLE
onOpen or onmessage cannot access textBox1

### ISSUE THREAD

**Issue by ellLazar** [statianzo/Fleck#165]
c# VS2010 
onOpen or onmessage cannot access textBox1.Append'
error:
 Cross-thread operation not valid: Control  accessed from a thread other than the thread it was created on...

any code example syntax help ?

**Comment by statianzo** [comment]
Fleck is running on another thread than your UI layer. You need to delegate to it.
http://stackoverflow.com/questions/14703698/invokedelegate
