### ISSUE TITLE
https and  Clent Certificate  (not working)

### ISSUE THREAD

**Issue by drormu1** [statianzo/Fleck#168]
just wonder if you  can help me with problems I found on prodction deployment.
My web site is https, and my end client must use X509 client Certfificate.

So I try use it via WSS
window.ws = new this.wsImpl('wss://' + '127.0.0.1' + ':' + this.settings.port + '/');

On the c# agent I init it to wss://....
and also generate self sign Cer via c#, and asign it to server.Certificate

but, still my agent  not get ready well, and javscript get   ReadyState == 3
any help ?

**Comment by statianzo** [comment]
Use localhost instead of 127.0.0.1 and the certificate common name has to match.

**Comment by drormu1** [comment]
thanks,

certiciate CN should be "localhgost"  or machineName ?


2016-03-15 14:55 GMT+02:00 Jason Staten <notifications@github.com>:

**Comment by statianzo** [comment]
It has to match whatever the URL is. In this case, localhost.
