### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by NVentimiglia** [statianzo/Fleck#171]
I was running some preference tests this weekend. The test included two applications. The first was an 'echo' server application. The second was a client application which instantiated up 1000 clients and spammed the server. Here are my notes.

**Microsoft Websockets**
- 400ms average round trip
- 2,000 messages per second.

**Fleck**
- 80ms average round trip
- 12,000 messages per second.
- Very fast "OnConnect" (I connected all clients in less than a minute with fleck).
- Friendly API

**NetGains**
- 25,000 messages per second
- Ping 40
- Built in metrics
- Ran into disconnection fault issue. I think I may off hit a limit, need to investigate more.

I bring this up wondering if there anything we could do to improve Fleck's performance. It may very well be good enough, but, part of me is wondering why NetGains is faster.

**Comment by statianzo** [comment]
Great work! I'm not sure of any low hanging fruit performance wise. Did you enable NoDelay on the `WebSocketServer.ListenerSocket`? Running a cpu profiler while benchmarking could be telling of where the bottleneck is.

Thanks for sharing your results.

**Comment by NVentimiglia** [comment]
Very strange. I turned on NoDelay and there was no change. Turning it off helped quite a bit. In fact, with Delay enabled Fleck is on par with NetGains (40ms and 25k rps on 1k connections).

Reading up on Nagle, I was anticipating an opposite result.
https://blogs.msdn.microsoft.com/windowsazurestorage/2010/06/25/nagles-algorithm-is-not-friendly-towards-small-requests/

**Comment by artfulhacker** [comment]
Great work! So by setting NoDelay to false you had better results with Fleck? We might try that on a bank of staging servers since we currently have it set to true.

**Comment by NVentimiglia** [comment]
Yeah, I tried again and could not find a difference. I agree we need a larger sample size.
