### ISSUE TITLE
Fleck.ConnectionNotAvailableException issue

### ISSUE THREAD

**Issue by ichbinwilly** [statianzo/Fleck#172]
I got the exception while my application is working. And the exception caused the crash inside the websocket application because of the **ConnectionNotAvailableException**.

```
Unhandled Exception: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As aresult, the unobserved exception was rethrown by the finalizer thread. ---> Fleck.ConnectionNotAvailableException: Data sent while closing or after close. Ignoring.
   --- End of inner exception stack trace ---
```

Look up the msdn, it said the unhandled exception could be thrown as an nested aggregate exceptions . I found the code related to the ConnectionNotAvailableException in line 91 of WebSocketConnection.cs file.

`taskForException.SetException(new ConnectionNotAvailableException(errorMessage));`

I think this line should be enclosing in the `try.. catch..` block, handling the unexpected exception and observe any of the inner exception.

```
try
{
  taskForException.SetException(new ConnectionNotAvailableException(errorMessage));
}
catch (AggregateException ae)
{
  foreach (var e in ae.InnerExceptions)
  {
      // Handle the custom exception.
      if (e is ConnectionNotAvailableException)
      {
          FleckLog.Error(e.Message);
      }
      // Rethrow any other exception.
      else
      {
          throw;
      }
  }
}
```

**Comment by Sios2016** [comment]
I'm having the same kind of problem with this particular line

> Type:   System.AggregateException 
>     Message:   A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. 
> 

> Exception: System.Runtime.Serialization.SerializationException
> 
> Message: Type 'Fleck.ConnectionNotAvailableException' in Assembly 'Fleck, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
> 
> StackTrace:    at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
>    at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
>    at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
>    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
>    at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.SerializeObject(Object obj, MemoryStream stm)
>    at System.AppDomain.Serialize(Object o)
>    at System.AppDomain.MarshalObject(Object o)

Every time this happens, the web application that runs on IIS 7 restarts.

I'm using the compiled version in my app, so I'll try to recompile it with your try catch to see if it solve my problem.

**Comment by darkl** [comment]
This happens when you call IWebSocketConnection.Send and it results with an exception, but your application is not aware about the exception.

Please see this [stackoverflow question](http://stackoverflow.com/questions/7883052/a-tasks-exceptions-were-not-observed-either-by-waiting-on-the-task-or-accessi) for further details.
