### ISSUE TITLE
Trying to figure out how to debug failed connections

### ISSUE THREAD

**Issue by jlindborg** [statianzo/Fleck#176]
I'm unsure how to dig deeper into what's happening during the web socket client connection process - I have users attaching and some succeed but a few fail - in my logs it looks like:

Good connection:
[Thread 044], [16/05/11 02:03:02], Client connected from 10.203.27.147:37623
[Thread 044], [16/05/11 02:03:02], 185 bytes read
[Thread 044], [16/05/11 02:03:02], Building Hybi-14 Response
[Thread 044], [16/05/11 02:03:02], Sent 129 bytes
[Thread 044], [16/05/11 02:03:02], New user connected - id=b60d309c-bb9c-427b-8188-fb13f78b30ba

Bad connection:
[Thread 091], [16/05/11 02:14:37], Client connected from 10.126.212.20:54042
[Thread 091], [16/05/11 02:14:37], 303 bytes read
[Thread 091], [16/05/11 02:14:37], Error while reading
[Thread 091], [16/05/11 02:14:37], Client connected from 10.126.212.20:54043
[Thread 091], [16/05/11 02:14:37], 303 bytes read
[Thread 091], [16/05/11 02:14:37], Error while reading
[Thread 091], [16/05/11 02:14:38], Client connected from 10.126.212.20:54044

But I don't know what "error while reading" means here - is there some sort of debug mode that can be turned on at the server level to kick out more details as to what's happening with these?  
Thanks much.

**Comment by statianzo** [comment]
Looks like you've changed `FleckLog.LogAction`. Exceptions get passed in when they occur. You just need to show them.
https://github.com/statianzo/Fleck/blob/master/src/Fleck/FleckLog.cs#L17

**Comment by jlindborg** [comment]
ah, duh - I did hook the action and log it out but did not add a check to see if the exception was null and include that in the output - I'll change that and see what it says...
thanks!

**Comment by jlindborg** [comment]
hmmm... well, the exception is logging out now but I'm not sure what it means:

[Thread 103], [16/05/11 08:49:11], Client connected from 10.77.250.38:50585
[Thread 012], [16/05/11 08:49:11], 303 bytes read
[Thread 012], [16/05/11 08:49:11], Error while reading
[Thread 012], [16/05/11 08:49:11], [Fleck WS Exception] Fleck.WebSocketException: Exception of type 'Fleck.WebSocketException' was thrown.
   at Fleck.HandlerFactory.BuildHandler(WebSocketHttpRequest request, Action`1 onMessage, Action onClose, Action`1 onBinary, Action`1 onPing, Action`1 onPong)
   at Fleck.WebSocketServer.<>c__DisplayClassb.<OnClientConnect>b__3(WebSocketHttpRequest r)
   at Fleck.WebSocketConnection.CreateHandler(IEnumerable`1 data)
   at Fleck.WebSocketConnection.<>c__DisplayClassf.<Read>b__e(Int32 r)
   at System.Threading.Tasks.Task.Execute()

any pointers as to what to tell the clients here?  It's odd because the same client code (according to them) will work when connecting around 8 or 10 times and then one will fail - it's consistently reproducible, though.

**Comment by statianzo** [comment]
Ahh, if it's a WebSocketException, check the `StatusCode` property and compare it with [WebSocketStatusCodes](https://github.com/statianzo/Fleck/blob/master/src/Fleck/WebSocketStatusCodes.cs). That will say why it failed. Given that stack trace, it blew up in BuildHandler, so that's likely an `UnsupportedDataType`, meaning that the version attempting to connect is invalid. See https://github.com/statianzo/Fleck/blob/master/src/Fleck/HandlerFactory.cs#L24

**Comment by jlindborg** [comment]
ok - I'll try casting the exception passed in as a WebSocketException and if it's not null dump out the additional info in there.
As a side note, is there an easy way to dump out the raw WebSocketHttpRequest received so we can try and figure out what they're doing different on requests that work and those that don't?
thanks much

**Comment by statianzo** [comment]
There's no built in logging of it, and the callback passed to `.Start` is fired after determining a valid handler for the requester's websocket protocol version. You'll need to make a custom build of Fleck to see it.

You could try moving the `_initialize(this)` call before `_handlerFactory` is invoked and inspecting the
`socket.ConnectionInfo` within the `.Start` callback. It provides access to the headers, request path, and other request info.
https://github.com/statianzo/Fleck/blob/master/src/Fleck/WebSocketConnection.cs#L141

```diff
    public void CreateHandler(IEnumerable<byte> data)
    {
      var request = _parseRequest(data.ToArray());
      if (request == null)
        return;
+      var subProtocol = _negotiateSubProtocol(request.SubProtocols);
+      ConnectionInfo = WebSocketConnectionInfo.Create(request, Socket.RemoteIpAddress, Socket.RemotePort, subProtocol);
+      _initialize(this);
      Handler = _handlerFactory(request);
      if (Handler == null)
        return;
-      var subProtocol = _negotiateSubProtocol(request.SubProtocols);
-      ConnectionInfo = WebSocketConnectionInfo.Create(request, Socket.RemoteIpAddress, Socket.RemotePort, subProtocol);
-      _initialize(this);

      var handshake = Handler.CreateHandshake(subProtocol);
      SendBytes(handshake, OnOpen);
    }
```
