### ISSUE TITLE
exception while sending negative char

### ISSUE THREAD

**Issue by jageee** [statianzo/Fleck#177]
In the client i convert char array to string and send it to this server,
but i get an exception when trying to send a negative char (>128):

5/15/2016 6:58:59 PM [Debug] Error while reading Fleck.WebSocketException: Exception of type 'Fleck.WebSocketException' was thrown.
   at Fleck.Handlers.Hybi13Handler.ReadUTF8PayloadData(Byte[] bytes) in .....Fleck\src\Fleck\Handlers\Hybi13Handler.cs:line 203

I guess the cause is that the function "ProcessFrame" handles case "FrameType.Text" and this case doesnt get negative char.

Should i invoke case "FrameType.Binary"?
If yes, how?

Thanks in advance.

**Comment by statianzo** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#send() with `Blob` or `ArrayBuffer`.

**Comment by jageee** [comment]
Thanks for the answer.

When i choose to send binary the server doesn't receive.
So, i added OnBinary handler to Server.cs  , but still don't receive. (please see below)
(OnMessage handler does receive string data from the client.)

server.Start(socket =>
                {
                    socket.OnOpen = () =>
                        {
                            Console.WriteLine("Open!");
                            allSockets.Add(socket);                             
                        };
                    socket.OnClose = () =>
                        {
                            Console.WriteLine("Close!");
                            allSockets.Remove(socket);
                        };
                    socket.OnMessage = message =>
                        {
                            Console.WriteLine(message);
                            allSockets.ToList().ForEach(s => s.Send("Echo: " + message));
                        };
                    **_socket.OnBinary = bMessage =>
                    {
                        Console.WriteLine(bMessage);
                    };_**

                });

**Comment by statianzo** [comment]
If the client doesn't set the frame type to binary, then Fleck has to interpret it as text.

**Comment by jageee** [comment]
Thanks
