### ISSUE TITLE
RFC6455

### ISSUE THREAD

**Issue by lineker** [statianzo/Fleck#187]
Does Fleck supports RFC6455 ?

**Comment by statianzo** [comment]
There are a few cases it doesn't meet the spec, but generally yes.

**Comment by statianzo** [comment]
See http://jxs.me/Fleck/

**Comment by johny7** [comment]
Fragmentation support would be the most useful and relatively easy to add. The fragmentation is supported by major browsers already.

**Comment by johny7** [comment]
You can add fragmentation on send by replacing Hybi13Handler.FrameData method with this code:
`
        public static byte[] FrameData(byte[] payload, FrameType frameType)
        {
            var memoryStream = new MemoryStream();

			const int framingSize = 131072;
			
            for( int startIdx = 0; startIdx < payload.Length; startIdx += framingSize )
			{
				bool final = startIdx + framingSize >= payload.Length;

				var data = FragmentData( payload.Skip( startIdx ).Take( framingSize ).ToArray(), frameType, final );
				memoryStream.Write( data, 0, data.Length );

				frameType = FrameType.Continuation;	//	Next fragmented packets should contain zero as 
			}

			return memoryStream.ToArray();
		}
        
		private static byte[] FragmentData( byte[] payload, FrameType frameType, bool final )
		{
			var memoryStream = new MemoryStream();
			byte op = (byte)((byte)frameType + (final ? 128 : 0) );

			memoryStream.WriteByte( op );

			if( payload.Length > UInt16.MaxValue )
			{
				memoryStream.WriteByte( 127 );
				var lengthBytes = payload.Length.ToBigEndianBytes<ulong>();
				memoryStream.Write( lengthBytes, 0, lengthBytes.Length );
			}
			else if( payload.Length > 125 )
			{
				memoryStream.WriteByte( 126 );
				var lengthBytes = payload.Length.ToBigEndianBytes<ushort>();
				memoryStream.Write( lengthBytes, 0, lengthBytes.Length );
			}
			else
			{
				memoryStream.WriteByte( (byte)payload.Length );
			}

			memoryStream.Write( payload, 0, payload.Length );

			return memoryStream.ToArray();
		}
`
