### ISSUE TITLE
Using Fleck in combination with custom implemented webserver on same port

### ISSUE THREAD

**Issue by tschombe** [statianzo/Fleck#188]
Hi,

I have a customer project where we use a self implemented webserver
(using .NET Framework 4.5) for static file serving and ajax request handling
based on WCF running on a designated port and Fleck for WebSocket
communication on a second port.

Now the customer requests that both communications share the same port.

Is there any chance to get this implemented without relying on 3rd party software?
I think in this issue https://github.com/statianzo/Fleck/issues/48 the requirement
is also mentioned, but I dont understand the exact solution and the code provided
by the user conradz since it is not complete, I miss the SocketWrapper implementation

maybe someone can point out the implementation in a bit mor detail

thanks in advance

**Comment by statianzo** [comment]
SocketWrapper is part of Fleck.
