### ISSUE TITLE
listen for wss:// and ws:// at the same time

### ISSUE THREAD

**Issue by jespertheend** [statianzo/Fleck#190]
I just started doing a bit of research on what is required to get my current setup working with https. I don't have wss:// working at all right now. But before I buy an expensive wildcard certificate, I'd like to know if it is possible to host a websocket server using Fleck that listens for both the wss:// and the ws:// protocol. Is there built in support for this or is it possible to create two separate 'new WebSocketServer()'s?

**Comment by statianzo** [comment]
You can create two servers, one plaintext the other ssl, bound on different ports. Also, before buying a cert, try testing using a self signed certificate or a temporary cert with zerossl (Let's Encrypt).

**Comment by jespertheend** [comment]
Alright thanks! Then that's what I'll do.
I already tried getting something to work using Let's Encrypt but what I was trying wasn't working because I wasn't using a domain to connect to the websocket, I was just using a raw ip.

I have a lot of sockets running on a bunch of different ips that are constantly changing, so I think the only option is to include the ip in a subdomain on the DNS records. At first I just wanted to use Let's Encrypt but it seems like they don't support wildcard domains, and renewing a certificate every time an ip changes isn't going to work either I think.
So that's why I think I'll have to buy a wildcard certificate somewhere (unless someone has a better idea). But using Let's Encrypt to test my setup before I buy something sounds like a good idea.
