### ISSUE TITLE
Suggested way to do auth? 

### ISSUE THREAD

**Issue by deanezra** [statianzo/Fleck#194]
I have read that most Websocket servers are using basic web auth as part of the handshake  (I assume in combination with wss). 

please can you suggest best approach for Websocket auth? 

I assume fleck doesn't support basic auth?

**Comment by AdrianBathurst** [comment]
I do authentication via cookies. Once logged into the site, the authentication cookie is passed along with the socket connection.  Interrogate the cookie as you wish from `socket.ConnectionInfo.Cookies`

**Comment by statianzo** [comment]
Also, if you want use a header like Authorization, it's available via `socket.ConnectionInfo.Headers["Authorization"]`

**Comment by deanezra** [comment]
I'm connecting using mobile based apps, so cookies is probably out. as for the header access, i do a similar thing at present in on connect. but was wondering if it would be better to do auth earlier in handshake instead of Websocket on connect. as I guess the client can send messages once it's told it's connected?

**Comment by deanezra** [comment]
How do I return a HTTP 401 (unauthorized) when the I have checked the credentials in socket header and they are incorrect?

**Comment by moxgeek** [comment]
> How do I return a HTTP 401 (unauthorized) when the I have checked the credentials in socket header and they are incorrect?

any news about throw a 401 error ?
