### ISSUE TITLE
How to save the user name and the corresponding Connection.id 

### ISSUE THREAD

**Issue by daoqiang** [statianzo/Fleck#196]
Hi，
Connection.id Can effectively distinguish the connection，but onOPEN function can not have parameters。
How can I bind user information to ID。To achieve the purpose of using the login user information to distinguish the connection。
thank you！

**Comment by statianzo** [comment]
You could use something like a dictionary that maps from the connection uuid to user information. Also, for authentication purposes, you can use connectioninfo.cookies.

**Comment by daoqiang** [comment]
Ok,thank you!
