### ISSUE TITLE
Create custom user id

### ISSUE THREAD

**Issue by cokeldv** [statianzo/Fleck#197]
I would like to send data to a specific user since for now the alerts / messages / events are sent to all users i am using the following code

> using System;
using System.Collections.Generic;
using System.Linq;
using Fleck;
using log4net;
using System.Text.RegularExpressions;

namespace Sockets
{
    public class WebSocketUser
    {
        public int ID { get; set; }

        public WebSocketUser(int ID)
        {
            this.ID = ID;
        }
    }
    public class WebSockets
    {
        private static readonly ILog log = LogManager.GetLogger("Sockets");

        public void Init()
        {
            //FleckLog.Level = LogLevel.Debug;
            var allSockets = new List<IWebSocketConnection>();
            var server = new WebSocketServer("ws://0.0.0.0:000");
            server.Start(socket =>
            {
                socket.OnOpen = () =>
                {
                    Console.WriteLine("Open!");
                    allSockets.Add(socket);
                };
                socket.OnClose = () =>
                {
                    Console.WriteLine("Close!");
                    allSockets.Remove(socket);
                };
                socket.OnMessage = message =>
                {
                    Console.WriteLine(message);
                    allSockets.ToList().ForEach(s => s.Send("Message: " + message));
                };
            });

        }
    }
}

**Comment by statianzo** [comment]
Unique identifiers are available through `socket.ConnectionInfo.Id`
