### ISSUE TITLE
Additional LogLevel:  Off

### ISSUE THREAD

**Issue by HarryPehkonen** [statianzo/Fleck#198]
Is it possible/appropriate to have a new LogLevel in FleckLog.cs called "Off"?  I assume it should have a high enumeration value (Int32.MaxValue?).

**Comment by statianzo** [comment]
If you want to stop all logging, you could set `FleckLog.LogAction` to be an empty action. Console logging is just a default implementation for convenience.

**Comment by HarryPehkonen** [comment]
Sounds good.  Thanks for your response!
