### ISSUE TITLE
OnClose issue is crashing Windows server 2016

### ISSUE THREAD

**Issue by normandeaup** [statianzo/Fleck#207]
Everything is working fine except 1 critical issue, after a couple minutes running with around 50 connected clients each sending 20 messages / second I randomly get this error, sometimes it loops for 2-3 seconds and it fixes itself and sometimes it keeps looping and it crashes the whole Windows server:

It seems to be falling in an infinite loop calling OnClose non-stop for the same client:

![image](https://user-images.githubusercontent.com/34383316/33787678-6f2054ec-dc3c-11e7-84ac-83dc59f10c96.png)

Anyone else is getting this issue?

**Comment by AdrianBathurst** [comment]
We have just started operating this on Windows server 2016 and initial tests are working ok.
