### ISSUE TITLE
Fleck - pings/pongs

### ISSUE THREAD

**Issue by ThePaceMaker** [statianzo/Fleck#211]
I see that the application does not support pings/pongs with regards to the RFC6455 standard. 

[http://jxs.me/Fleck/](http://jxs.me/Fleck/)

Is it in the roadmap to include it or fix it, in the near future?

**Comment by statianzo** [comment]
That test run is out of date. Fleck supports ping and pong. See the IWebsocketConnecton interface for how to send and respond those frame types.

**Comment by ThePaceMaker** [comment]
Just did the tests myself and I see that it has been implemented. Awesome little repository!
