### ISSUE TITLE
Unable to install package "Fleck 0.14.0.59",MonoAndroid error

### ISSUE THREAD

**Issue by hncc** [statianzo/Fleck#212]
Unable to install package "Fleck 0.14.0.59". You are trying to install this package on a project that targets "MonoAndroid, Version = v5.1", but the package does not contain any assembly references or content files that are compatible with the framework. For more information, contact the package author. 。Can u help me?

**Comment by hncc** [comment]
I want to use it in Visual studio 2017 to dev xamarin.Android, but IDE  tell me the error...,
Is there any solution?

**Comment by statianzo** [comment]
Can you clone this repository and build Fleck against the MonoAndroid target? The DLL in Nuget probably doesn't work directly with MonoAndroid.
