### ISSUE TITLE
0 Bytes read. Closing Randomly

### ISSUE THREAD

**Issue by JayCustom** [statianzo/Fleck#218]
Hello! Me Again.

I am having an issue where the packets disconnect randomly - even when the user is still connected... Is there a timeout?

**Comment by statianzo** [comment]
There's no timeout in Fleck. The underlying TCP socket surely has one, but I would expect it to keep itself open while connected.

Have you tried sending pings on a timer to see if that prevents the issue?
Can it be reproduced with a single connection?
Can it happen shortly the server starts, or does it only occur after running for awhile?
Can you capture some logs with FleckLog.Level = Debug?

**Comment by JayCustom** [comment]
Have you tried sending pings on a timer to see if that prevents the issue? - I have. Unsure to tell, I have stayed connected both with and without pings. It occurs randomly after no sockets have been sent for awhile.
Can it be reproduced with a single connection? - Happens to multiple users, connecting from multiple IP addresses.
Can it happen shortly the server starts, or does it only occur after running for awhile? - Both.
Can you capture some logs with FleckLog.Level = Debug? - Not sure where to create the logs, because it just happens. It just closes itself. I have even put on the server side to restart after connection closes, and it doesn't restart.
