### ISSUE TITLE
CPU Perfomance

### ISSUE THREAD

**Issue by Saloed123** [statianzo/Fleck#240]
Hello, we are use Fleck server after many other libraries.
How we can bore with CPU, because after connect 100 clients, we have problem with perfomance (CPU) always 70-100% with Xeon E3-1240 3.7Ghz.

We use 2 fleck server in one application, for public clients and for microservices.

Our settings for server 
```
    var server = new Fleck.WebSocketServer($"ws://127.0.0.1:{port}")
            {
                RestartAfterListenError = true,
                ListenerSocket =
                {
                    NoDelay = true,
                }
            };
            
            //server.ListenerSocket.LocalEndPoint = new IPEndPoint(new IPAddress(2130706433), port);
            server.Start(socket =>
            {
                    var client = factory.CreateClient();
                    client.SetupConnection(socket);
            });
```
Every microservices use several connections to main app, and random take one session for sending data.

How we can improve perfomance of our server?

**Comment by statianzo** [comment]
Try doing some performance profiling to see where cpu load is spent
https://msdn.microsoft.com/en-us/library/ms182372.aspx

If you see the CPU time is within Fleck, and not your own application then please share your findings.
