### ISSUE TITLE
Performance is not good

### ISSUE THREAD

**Issue by issingle** [statianzo/Fleck#248]
![image](https://user-images.githubusercontent.com/2561602/46258553-641b1080-c4ff-11e8-91f6-aa8c74d6f69f.png)

100client  20qps/client

server perfmon counter:
![image](https://user-images.githubusercontent.com/2561602/46258652-2a4b0980-c501-11e8-86de-acad90e6b759.png)

Fleck server CPU 26%  
server pc cpu: I5-3570 ram:16GB

**Comment by issingle** [comment]
500 client 
every client qps from 20  down to 10.
Server CPU 50%
![image](https://user-images.githubusercontent.com/2561602/46258728-1a7ff500-c502-11e8-9165-714ddd6ca1fd.png)

**Comment by issingle** [comment]
Hybi13Handler.cs
`                var payload = data
                                .Skip(index)
                                .Take(payloadLength)
                                .Select((x, i) => (byte)(x ^ maskBytes[i % 4]));


                readState.Data.AddRange(payload);  //<-------------bad performance
                data.RemoveRange(0, index + payloadLength);`
![image](https://user-images.githubusercontent.com/2561602/46258763-86625d80-c502-11e8-841e-351176668552.png)

**Comment by notgiven688** [comment]
From a first look the problem here could be that every single byte is added to the readState.data since they are passed to addRange via an IEnumerable object. Which is expected to be slow. 

Removing

`               var payload = data
                                .Skip(index)
                                .Take(payloadLength)
                                .Select((x, i) => (byte)(x ^ maskBytes[i % 4]));


                readState.Data.AddRange(payload);
`

and adding

`               
                byte[] playloadData = new byte[payloadLength];
                for (int i = 0; i < payloadLength; i++)
                    playloadData[i] = (byte)(data[index+i] ^ maskBytes[i % 4]);

                readState.Data.AddRange(playloadData);
`

should be better because AddRange(..) falls back to Array.Copy. What do you think @statianzo ?

**Comment by statianzo** [comment]
Worth trying. If you put together a PR, I'll get it merged and released.

**Comment by statianzo** [comment]
Released as `1.0.4`. #260
