### ISSUE TITLE
A Suggest

### ISSUE THREAD

**Issue by slyzly** [statianzo/Fleck#250]
nodejs
var util = require('util');
var url = require('url');
var server = require('ws').Server;
var wss = new server({ port: 8181,**verifyClient: ClientVerify** });
wss.on('connection', function (ws){
   console.log('client connected');
   ws.on('message', function (message) {
        ws.send("message received!");
   });
   ws.on('close', function (close) {
        console.log("client closed");
   });
});

function ClientVerify(info) {
   var ret = false;
   var params = url.parse(info.req.url, true).query;
   if (params["id"] == "luoc83" &&params["key"] == "123456") {
        ret = true;//pass
   }
   return ret;  
}

myws.html
<!DOCTYPE html PUBLIC"-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<htmlxmlns="http://www.w3.org/1999/xhtml">
<head>
   <script type="text/javascript" language="javascript">
        var ws;
         var user = "luoc83";
         var psw = "123456";
        function Connect() {
            ws = new WebSocket("ws://localhost:8181?id="+user+"&key="+psw);
            ws.onopen = function (e) {
                 alert("connectsuccess");
            }
            ws.onclose = function () {
                alert("close");
            }
            ws.onerror = function (e) {
                alert("connecterror!");
            }; 
            ws.onmessage = function (event) {
                alert(event.data);
            };
        }
   </script>
</head>
<body >
<button onclick="Connect()">test</button>
</body>
</html>

**Comment by statianzo** [comment]
Are you suggesting adding a `verifyClient` option to WebSocketServer?

**Comment by slyzly** [comment]
Yes, it is very convenient to use.
