### ISSUE TITLE
Sending text messages to specific clients

### ISSUE THREAD

**Issue by OnlyFreeUsername** [statianzo/Fleck#277]
I'm not sure if I'm missing something here or if this behaviour is simply not planned. How do I send messages (preferably strings) from the server to the clients? Especially, given I have the connection ID of the client, how do I send a message to this specific client? I have my socket server setup as below:

```c#
var webSocketServer = new WebSocketServer("ws://0.0.0.0:8181");
webSocketServer.SupportedSubProtocols = new[] { "main" };
void config(IWebSocketConnection socket) {
    socket.OnOpen = () => OnOpen(socket);
    socket.OnClose = () => OnClose(socket);
    socket.OnMessage = (message) => OnMessage(socket, message);
}
webSocketServer.Start(config);
// expected functionality
webSocketServer.Broadcast("Hello all clients!");
webSocketServer.Send("689e9933-xxxx-xxxx-xxxx-06296ae468c7", "Hello specific client!");
```

**Comment by AdrianBathurst** [comment]
See "Server" section in this post: https://github.com/statianzo/Fleck/issues/215#issuecomment-367394401

In OnOpen, store the `socket` in a thread safe collection that holds all client connections, e.g. `allSockets` in that example. `socket` is the socket connected to a specific client.

When you want to send a message to a specific client, filter the client specific socket from the `allSockets` collection, then apply a `Send` to that socket.

**Comment by OnlyFreeUsername** [comment]
Thanks, that was exactly what i was looking for :)
