### ISSUE TITLE
可以在和IIS共用一个服务器端口么

### ISSUE THREAD

**Issue by guyixn** [statianzo/Fleck#284]
### 公司的内网限制的问题，只允许开放80端口，而WS使用的是8181端口，所以建立不了WS连接；我想WS和IIS共用一个80端口，可以么？有什么可用的解决方案么？

**Comment by AdrianBathurst** [comment]
如果要共享端口 80，请使用 IIS 的"反向代理"。

**Comment by HyattJobs** [comment]
> 如果要共享端口 80，请使用 IIS 的"反向代理"。

解决了，我用的nginx的反向代理。。。

**Comment by zkna** [comment]
已解决
