### ISSUE TITLE
Set SocketOptionName.ReuseAddress on Linux too

### ISSUE THREAD

**Issue by xPaw** [statianzo/Fleck#292]
Right now its only set for Windows for some reason:
https://github.com/statianzo/Fleck/blob/2f5365ed229030d0c62b08dd511b9e7da3eb68c3/src/Fleck/WebSocketServer.cs#L31-L36

Running on Linux under .NET Core, I get "already in use" after restarting the app due to TIME_WAIT connections.

`ISocket` does not expose `SetSocketOption`, so I can't do it myself.

**Comment by statianzo** [comment]
Could you put together a PR for not requiring Windows to set this option? Sounds like it came from an unintentional change.

https://github.com/statianzo/Fleck/issues/243#issuecomment-478946947

**Comment by xPaw** [comment]
I made a pr: #294, shouldn't be any problem to always set that?
