### ISSUE TITLE
Linux server with windows client error connection

### ISSUE THREAD

**Issue by Dmitriy147** [statianzo/Fleck#308]
Good day! I have a .net 4.5 project where i have created a working server for windows console app. Next step - i am trying to recompile my server to  .net 5 console app of my fleck server. The problem is to connect with my windows client to .net 5 fleck server starting in  linux...By the way, my linux (!!!) and windows client succesfully connects to fleck server of .net 5 staring in windows.
Version of Fleck v.1.1.0, Linux - debian 10, Windows 10x64..
I have checked another websocket server lib (Ninja.websocket), where server is fine working with my client in any variants. The main is that I compile my websocket server unnder windows in ms visual studio 2019 and try to make it works under  both win and linux..

**Comment by statianzo** [comment]
What errors and logs are you seeing? What client are you using to connect to Fleck? Have you tried a different client like a browser? 

Are you using IPv6?

There are two places Fleck checks if it is running on Windows. Maybe that's where the issue stems from

https://github.com/statianzo/Fleck/blob/master/src/Fleck/WebSocketServer.cs#L34

https://github.com/statianzo/Fleck/blob/d7634519dc872a95a9c28bde8d8cb20241890ef2/src/Fleck/SocketWrapper.cs#L66

**Comment by Dmitriy147** [comment]
Solved! Another lib in the project did not let to established the connection.. sorry, thank's!!
