### ISSUE TITLE
Handshake SupportedSubProtocols does not work.

### ISSUE THREAD

**Issue by ilsnk** [statianzo/Fleck#319]
![image](https://user-images.githubusercontent.com/44324620/137599282-1c00628a-ac68-4cda-bf8b-0d115d3da2fb.png)
SupportedSubProtocols  from client always null: ws://127.0.0.1:5000/chat/

**Comment by ilsnk** [comment]
there is nothing here (null), no matter how I send this SubProtocol


![image](https://user-images.githubusercontent.com/44324620/137600439-47e07ba2-ac09-4f29-bf08-e92f69bec30b.png)

**Comment by ilsnk** [comment]
What I was looking for was "path", most likely the sub-protocol needs to be sent in a different form. This site helped me figure it out. 

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

**Comment by statianzo** [comment]
Subprotocols are added in JavaScript by the second argument of the WebSocket constructor. Glad to hear that path will work for you though.
