### ISSUE TITLE
net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by 2061159711** [statianzo/Fleck#323]
当我客户端和服务器创建连接时出错，
服务器端：
![image](https://user-images.githubusercontent.com/49550413/154633639-6c7e4b19-cbe5-45c6-950f-37488bb67c0d.png)
客户端：
![image](https://user-images.githubusercontent.com/49550413/154633719-9dc85904-0a85-49cf-b1a2-6389a3505256.png)
错误：
![image](https://user-images.githubusercontent.com/49550413/154633781-9b159b22-d39e-459c-a242-127f35036a06.png)

**Comment by statianzo** [comment]
Try using a newer SSL protocol
```csharp
server.EnabledSslProtocols = SslProtocols.Tls12;
```

**Comment by 2061159711** [comment]
好的！非常感谢您的回复，问题已经解决，就是这个Tls版本的问题，指定到Tls1.2版本再测试就好了。
