### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Slluxx** [statianzo/Fleck#327]
I see (currently) 52 Issues and 13 Pull requests. @statianzo Do you still work on this? If no, you should archive this repo or state that you abandoned the project.

The issues seem to be major ones and are really frightening to look at, especially if you want to start a new project with Fleck as included Lib.

**Comment by AdrianBathurst** [comment]
Not to be abandoned...we use it with no issues.

**Comment by Slluxx** [comment]
Dont want to be rude but just because it works for you (or just because you havent noticed issues) doesnt mean that it actually runs without issues. Statianzo has not made any contribution to any github repository in **almost a year** and other people certainly do have real issues with it. Also, a project can be abandoned even though you still use it.

**Comment by statianzo** [comment]
Hi @Slluxx 

I don’t actively work on Fleck.

That said, issues being opened do sometimes get a response (including me). Archiving would close that forum.

There are other contributors to Fleck. If you would like to as well, I’m open to it.
