### ISSUE TITLE
Question: SSL Client Certificate difference

### ISSUE THREAD

**Issue by sertunc** [statianzo/Fleck#329]
Hello, first of all, thank you for this repo.

I want to generate certificate for both server and client but if the client's certificate is different ca, it has not to be able connect.

How can I do that ?

Thank you.

**Comment by AdrianBathurst** [comment]
You probably want to describe your environment/issue a bit more.

You can generate a test certificate by following this https://github.com/statianzo/Fleck/issues/214#issuecomment-364413879

**Comment by sertunc** [comment]
> You probably want to describe your environment/issue a bit more.
> 
> You can generate a test certificate by following this [#214 (comment)](https://github.com/statianzo/Fleck/issues/214#issuecomment-364413879)

i just want to verify client certificate. if client certificate different, i want to throw an exception.

**Comment by AdrianBathurst** [comment]
Can't help you there. Let the browser/webserver deal with the ssl handshake?

**Comment by sertunc** [comment]
> Can't help you there. Let the browser/webserver deal with the ssl handshake?

if i solve the problem i will pr about it
