### ISSUE TITLE
Is Send Blocking ?

### ISSUE THREAD

**Issue by vaghelan** [statianzo/Fleck#87]
Hi,

I am testing the Fleck API to implement the websocket server. I am transporting large amount of data (like video frames) over the websocket. My server is able to generate 30 frames per sec but when I write to the socket it goes down t 20 frames per sec. I do not see any Async API for the Send call. I think since it is a blocking API, my server perf goes down.

Kindly advise.

**Comment by galbarm** [comment]
Joining the question - is it possible to register for a callback or is there any other way to simulate the blocking behavior?
I need to guarantee that the messages I'm sending to the client, will be arriving in a certain order...

**Comment by statianzo** [comment]
There is no register for a callback exposed through the api at the moment. The signature of Send could be changed from void to Task to expose a way of hooking into the underlying Task though.

**Comment by galbarm** [comment]
Thanks,
I've issued a pull request
https://github.com/statianzo/Fleck/pull/126
